server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
  rabbitmq:
    host: 192.168.159.129 #主机
    username: leyou #用户名
    password: leyou #密码
    virtual-host: /leyou #虚拟消息服务器
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
fdfs:
  so-timeout: 1510
  connect-timeout: 601
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 192.168.159.129:22122
