server:
  port: 8088
spring:
  application:
    name: sms-service
  redis:
    host: 192.168.159.129
  rabbitmq:
    host: 192.168.159.129
    username: leyou
    password: leyou
    virtual-host: /leyou
