server:
  port: 8089
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.159.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ly:
  jwt:
    cookieName: LY_TOKEN
    pubKeyPath: C:\\Temp\\rsa\\rsa.pub # 公钥地址